title: CMD-DOTCOM
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://cmd-dotcom.github.io

aux_links:
  Template Repository: https://github.com/cmd-dotcom/cmd-dotcom.github.io
